// Forward declarations for org.apache.poi.ss.usermodel
#pragma once


namespace poi
{
    namespace ss
    {
        namespace usermodel
        {
            struct AutoFilter;
            class BorderExtent;
            struct BorderFormatting;
            class BorderStyle;
            class BuiltinFormats;
            struct Cell;
            class CellCopyPolicy;
            class CellCopyPolicy_Builder;
            struct CellRange;
            struct CellStyle;
            class CellType;
            class CellValue;
            struct Chart;
            struct ChildAnchor;
            struct ClientAnchor;
            class ClientAnchor_AnchorType;
            struct Color;
            struct ColorScaleFormatting;
            struct Comment;
            class ComparisonOperator;
            struct ConditionFilterData;
            class ConditionFilterType;
            class ConditionType;
            struct ConditionalFormatting;
            struct ConditionalFormattingRule;
            struct ConditionalFormattingThreshold;
            class ConditionalFormattingThreshold_RangeType;
            struct CreationHelper;
            struct DataBarFormatting;
            class DataConsolidateFunction;
            struct DataFormat;
            class DataFormatter;
            class DataFormatter_CellFormatResultWrapper;
            class DataFormatter_ConstantStringFormat;
            class DataFormatter_InternalDecimalFormatWithScale;
            class DataFormatter_LocaleChangeObservable;
            class DataFormatter_PhoneFormat;
            class DataFormatter_SSNFormat;
            class DataFormatter_ZipPlusFourFormat;
            struct DataValidation;
            struct DataValidationConstraint;
            class DataValidationConstraint_OperatorType;
            class DataValidationConstraint_ValidationType;
            struct DataValidationHelper;
            class DataValidation_ErrorStyle;
            class DateUtil;
            class DateUtil_1;
            class DateUtil_FormatException;
            struct DifferentialStyleProvider;
            struct Drawing;
            class ExcelGeneralNumberFormat;
            class ExcelNumberFormat;
            class ExcelStyleDateFormatter;
            class ExtendedColor;
            class FillPatternType;
            struct Font;
            class FontCharset;
            class FontFamily;
            struct FontFormatting;
            class FontScheme;
            class FontUnderline;
            struct Footer;
            class FormulaError;
            struct FormulaEvaluator;
            class FractionFormat;
            struct Header;
            struct HeaderFooter;
            class HorizontalAlignment;
            struct Hyperlink;
            struct IconMultiStateFormatting;
            class IconMultiStateFormatting_IconSet;
            class IgnoredErrorType;
            class IndexedColors;
            struct Name;
            struct ObjectData;
            class PageOrder;
            class PaperSize;
            struct PatternFormatting;
            struct Picture;
            struct PictureData;
            class PrintCellComments;
            class PrintOrientation;
            struct PrintSetup;
            struct RichTextString;
            struct Row;
            class Row_MissingCellPolicy;
            struct Shape;
            struct ShapeContainer;
            class ShapeTypes;
            struct Sheet;
            struct SheetConditionalFormatting;
            class SheetVisibility;
            struct SimpleShape;
            struct Table;
            struct TableStyle;
            struct TableStyleInfo;
            class TableStyleType;
            class TableStyleType_1;
            class TableStyleType_10;
            class TableStyleType_11;
            class TableStyleType_12;
            class TableStyleType_13;
            class TableStyleType_2;
            class TableStyleType_3;
            class TableStyleType_4;
            class TableStyleType_5;
            class TableStyleType_6;
            class TableStyleType_7;
            class TableStyleType_8;
            class TableStyleType_9;
            struct Textbox;
            class VerticalAlignment;
            struct Workbook;
        } // usermodel
    } // ss
} // poi
