// Forward declarations for org.apache.poi.hssf.record
#pragma once


namespace org
{
    namespace apache
    {
        namespace poi
        {
            namespace hssf
            {
                namespace record
                {
                    class AbstractEscherHolderRecord;
                    class ArrayRecord;
                    class AutoFilterInfoRecord;
                    class BOFRecord;
                    class BackupRecord;
                    struct BiffHeaderInput;
                    class BlankRecord;
                    class BookBoolRecord;
                    class BoolErrRecord;
                    class BottomMarginRecord;
                    class BoundSheetRecord;
                    class BoundSheetRecord_1;
                    class CFHeader12Record;
                    class CFHeaderBase;
                    class CFHeaderRecord;
                    class CFRule12Record;
                    class CFRuleBase;
                    class CFRuleBase_ComparisonOperator;
                    class CFRuleRecord;
                    class CRNCountRecord;
                    class CRNRecord;
                    class CalcCountRecord;
                    class CalcModeRecord;
                    class CellRecord;
                    struct CellValueRecordInterface;
                    class CodepageRecord;
                    class ColumnInfoRecord;
                    class CommonObjectDataSubRecord;
                    class ContinueRecord;
                    class CountryRecord;
                    class DBCellRecord;
                    class DBCellRecord_Builder;
                    class DConRefRecord;
                    class DSFRecord;
                    class DVALRecord;
                    class DVRecord;
                    class DateWindow1904Record;
                    class DefaultColWidthRecord;
                    class DefaultRowHeightRecord;
                    class DeltaRecord;
                    class DimensionsRecord;
                    class DrawingGroupRecord;
                    class DrawingRecord;
                    class DrawingRecordForBiffViewer;
                    class DrawingSelectionRecord;
                    class DrawingSelectionRecord_OfficeArtRecordHeader;
                    class EOFRecord;
                    class EmbeddedObjectRefSubRecord;
                    class EndSubRecord;
                    class EscherAggregate;
                    class EscherAggregate_createAggregate_1;
                    class EscherAggregate_getRecordSize_3;
                    class EscherAggregate_serialize_2;
                    class ExtSSTRecord;
                    class ExtSSTRecord_InfoSubRecord;
                    class ExtendedFormatRecord;
                    class ExternSheetRecord;
                    class ExternSheetRecord_RefSubRecord;
                    class ExternalNameRecord;
                    class FeatHdrRecord;
                    class FeatRecord;
                    class FilePassRecord;
                    class FileSharingRecord;
                    class FnGroupCountRecord;
                    class FontRecord;
                    class FooterRecord;
                    class FormatRecord;
                    class FormulaRecord;
                    class FormulaRecord_SpecialCachedValue;
                    class FtCblsSubRecord;
                    class FtCfSubRecord;
                    class FtPioGrbitSubRecord;
                    class GridsetRecord;
                    class GroupMarkerSubRecord;
                    class GutsRecord;
                    class HCenterRecord;
                    class HeaderFooterBase;
                    class HeaderFooterRecord;
                    class HeaderRecord;
                    class HideObjRecord;
                    class HorizontalPageBreakRecord;
                    class HyperlinkRecord;
                    class HyperlinkRecord_GUID;
                    class IndexRecord;
                    class InterfaceEndRecord;
                    class InterfaceHdrRecord;
                    class IterationRecord;
                    class LabelRecord;
                    class LabelSSTRecord;
                    class LbsDataSubRecord;
                    class LbsDataSubRecord_LbsDropData;
                    class LeftMarginRecord;
                    class MMSRecord;
                    struct Margin;
                    class MergeCellsRecord;
                    class MulBlankRecord;
                    class MulRKRecord;
                    class MulRKRecord_RkRec;
                    class NameCommentRecord;
                    class NameRecord;
                    class NameRecord_Option;
                    class NoteRecord;
                    class NoteStructureSubRecord;
                    class NumberRecord;
                    class ObjRecord;
                    class ObjectProtectRecord;
                    class OldCellRecord;
                    class OldFormulaRecord;
                    class OldLabelRecord;
                    class OldSheetRecord;
                    class OldStringRecord;
                    class PageBreakRecord;
                    class PageBreakRecord_Break;
                    class PaletteRecord;
                    class PaletteRecord_PColor;
                    class PaneRecord;
                    class PasswordRecord;
                    class PasswordRev4Record;
                    class PrecisionRecord;
                    class PrintGridlinesRecord;
                    class PrintHeadersRecord;
                    class PrintSetupRecord;
                    class ProtectRecord;
                    class ProtectionRev4Record;
                    class RKRecord;
                    class RecalcIdRecord;
                    class Record;
                    class RecordBase;
                    class RecordFactory;
                    class RecordFactoryInputStream;
                    class RecordFactoryInputStream_StreamEncryptionInfo;
                    struct RecordFactory_I_RecordCreator;
                    class RecordFactory_ReflectionConstructorRecordCreator;
                    class RecordFactory_ReflectionMethodRecordCreator;
                    class RecordInputStream;
                    class RecordInputStream_LeftoverDataException;
                    class RecordInputStream_SimpleHeaderInput;
                    class RefModeRecord;
                    class RefreshAllRecord;
                    class RightMarginRecord;
                    class RowRecord;
                    class SCLRecord;
                    class SSTDeserializer;
                    class SSTRecord;
                    class SSTSerializer;
                    class SaveRecalcRecord;
                    class ScenarioProtectRecord;
                    class SelectionRecord;
                    class SharedFormulaRecord;
                    class SharedValueRecordBase;
                    class StandardRecord;
                    class StringRecord;
                    class StyleRecord;
                    class SubRecord;
                    class SubRecord_UnknownSubRecord;
                    class SupBookRecord;
                    class TabIdRecord;
                    class TableRecord;
                    class TableStylesRecord;
                    class TextObjectRecord;
                    class TopMarginRecord;
                    class UncalcedRecord;
                    class UnknownRecord;
                    class UseSelFSRecord;
                    class UserSViewBegin;
                    class UserSViewEnd;
                    class VCenterRecord;
                    class VerticalPageBreakRecord;
                    class WSBoolRecord;
                    class WindowOneRecord;
                    class WindowProtectRecord;
                    class WindowTwoRecord;
                    class WriteAccessRecord;
                    class WriteProtectRecord;
                } // record
            } // hssf
        } // poi
    } // apache
} // org
