// Generated from /POI/java/org/apache/poi/hssf/record/chart/TextRecord.java

#pragma once

#include <fwd-POI.hpp>
#include <java/lang/fwd-POI.hpp>
#include <org/apache/poi/hssf/record/fwd-POI.hpp>
#include <org/apache/poi/hssf/record/chart/fwd-POI.hpp>
#include <org/apache/poi/util/fwd-POI.hpp>
#include <org/apache/poi/hssf/record/StandardRecord.hpp>

struct default_init_tag;

class poi::hssf::record::chart::TextRecord final
    : public ::poi::hssf::record::StandardRecord
{

public:
    typedef ::poi::hssf::record::StandardRecord super;
    static constexpr int16_t sid { int16_t(4133) };

private:
    static ::poi::util::BitField* dataLabelPlacement_;
    static ::poi::util::BitField* autoColor_;
    static ::poi::util::BitField* showKey_;
    static ::poi::util::BitField* showValue_;
    static ::poi::util::BitField* vertical_;
    static ::poi::util::BitField* autoGeneratedText_;
    static ::poi::util::BitField* generated_;
    static ::poi::util::BitField* autoLabelDeleted_;
    static ::poi::util::BitField* autoBackground_;
    static ::poi::util::BitField* rotation_;
    static ::poi::util::BitField* showCategoryLabelAsPercentage_;
    static ::poi::util::BitField* showValueAsPercentage_;
    static ::poi::util::BitField* showBubbleSizes_;
    static ::poi::util::BitField* showLabel_;
    int8_t field_1_horizontalAlignment {  };

public:
    static constexpr int8_t HORIZONTAL_ALIGNMENT_LEFT { int8_t(1) };
    static constexpr int8_t HORIZONTAL_ALIGNMENT_CENTER { int8_t(2) };
    static constexpr int8_t HORIZONTAL_ALIGNMENT_BOTTOM { int8_t(3) };
    static constexpr int8_t HORIZONTAL_ALIGNMENT_JUSTIFY { int8_t(4) };

private:
    int8_t field_2_verticalAlignment {  };

public:
    static constexpr int8_t VERTICAL_ALIGNMENT_TOP { int8_t(1) };
    static constexpr int8_t VERTICAL_ALIGNMENT_CENTER { int8_t(2) };
    static constexpr int8_t VERTICAL_ALIGNMENT_BOTTOM { int8_t(3) };
    static constexpr int8_t VERTICAL_ALIGNMENT_JUSTIFY { int8_t(4) };

private:
    int16_t field_3_displayMode {  };

public:
    static constexpr int16_t DISPLAY_MODE_TRANSPARENT { int16_t(1) };
    static constexpr int16_t DISPLAY_MODE_OPAQUE { int16_t(2) };

private:
    int32_t field_4_rgbColor {  };
    int32_t field_5_x {  };
    int32_t field_6_y {  };
    int32_t field_7_width {  };
    int32_t field_8_height {  };
    int16_t field_9_options1 {  };

public:
    static constexpr int16_t ROTATION_NONE { int16_t(0) };
    static constexpr int16_t ROTATION_TOP_TO_BOTTOM { int16_t(1) };
    static constexpr int16_t ROTATION_ROTATED_90_DEGREES { int16_t(2) };
    static constexpr int16_t ROTATION_ROTATED_90_DEGREES_CLOCKWISE { int16_t(3) };

private:
    int16_t field_10_indexOfColorValue {  };
    int16_t field_11_options2 {  };

public:
    static constexpr int16_t DATA_LABEL_PLACEMENT_CHART_DEPENDENT { int16_t(0) };
    static constexpr int16_t DATA_LABEL_PLACEMENT_OUTSIDE { int16_t(1) };
    static constexpr int16_t DATA_LABEL_PLACEMENT_INSIDE { int16_t(2) };
    static constexpr int16_t DATA_LABEL_PLACEMENT_CENTER { int16_t(3) };
    static constexpr int16_t DATA_LABEL_PLACEMENT_AXIS { int16_t(4) };
    static constexpr int16_t DATA_LABEL_PLACEMENT_ABOVE { int16_t(5) };
    static constexpr int16_t DATA_LABEL_PLACEMENT_BELOW { int16_t(6) };
    static constexpr int16_t DATA_LABEL_PLACEMENT_LEFT { int16_t(7) };
    static constexpr int16_t DATA_LABEL_PLACEMENT_RIGHT { int16_t(8) };
    static constexpr int16_t DATA_LABEL_PLACEMENT_AUTO { int16_t(9) };
    static constexpr int16_t DATA_LABEL_PLACEMENT_USER_MOVED { int16_t(10) };

private:
    int16_t field_12_textRotation {  };
protected:
    void ctor();
    void ctor(::poi::hssf::record::RecordInputStream* in);

public:
    ::java::lang::String* toString() override;
    void serialize(::poi::util::LittleEndianOutput* out) override;

public: /* protected */
    int32_t getDataSize() override;

public:
    int16_t getSid() override;
    ::java::lang::Object* clone() override;
    int8_t getHorizontalAlignment();
    void setHorizontalAlignment(int8_t field_1_horizontalAlignment);
    int8_t getVerticalAlignment();
    void setVerticalAlignment(int8_t field_2_verticalAlignment);
    int16_t getDisplayMode();
    void setDisplayMode(int16_t field_3_displayMode);
    int32_t getRgbColor();
    void setRgbColor(int32_t field_4_rgbColor);
    int32_t getX();
    void setX(int32_t field_5_x);
    int32_t getY();
    void setY(int32_t field_6_y);
    int32_t getWidth();
    void setWidth(int32_t field_7_width);
    int32_t getHeight();
    void setHeight(int32_t field_8_height);
    int16_t getOptions1();
    void setOptions1(int16_t field_9_options1);
    int16_t getIndexOfColorValue();
    void setIndexOfColorValue(int16_t field_10_indexOfColorValue);
    int16_t getOptions2();
    void setOptions2(int16_t field_11_options2);
    int16_t getTextRotation();
    void setTextRotation(int16_t field_12_textRotation);
    void setAutoColor(bool value);
    bool isAutoColor();
    void setShowKey(bool value);
    bool isShowKey();
    void setShowValue(bool value);
    bool isShowValue();
    void setVertical(bool value);
    bool isVertical();
    void setAutoGeneratedText(bool value);
    bool isAutoGeneratedText();
    void setGenerated(bool value);
    bool isGenerated();
    void setAutoLabelDeleted(bool value);
    bool isAutoLabelDeleted();
    void setAutoBackground(bool value);
    bool isAutoBackground();
    void setRotation(int16_t value);
    int16_t getRotation();
    void setShowCategoryLabelAsPercentage(bool value);
    bool isShowCategoryLabelAsPercentage();
    void setShowValueAsPercentage(bool value);
    bool isShowValueAsPercentage();
    void setShowBubbleSizes(bool value);
    bool isShowBubbleSizes();
    void setShowLabel(bool value);
    bool isShowLabel();
    void setDataLabelPlacement(int16_t value);
    int16_t getDataLabelPlacement();

    // Generated
    TextRecord();
    TextRecord(::poi::hssf::record::RecordInputStream* in);
protected:
    TextRecord(const ::default_init_tag&);


public:
    static ::java::lang::Class *class_();
    static void clinit();
    int32_t serialize(int32_t offset, ::int8_tArray* data);
    ::int8_tArray* serialize();

private:
    static ::poi::util::BitField*& dataLabelPlacement();
    static ::poi::util::BitField*& autoColor();
    static ::poi::util::BitField*& showKey();
    static ::poi::util::BitField*& showValue();
    static ::poi::util::BitField*& vertical();
    static ::poi::util::BitField*& autoGeneratedText();
    static ::poi::util::BitField*& generated();
    static ::poi::util::BitField*& autoLabelDeleted();
    static ::poi::util::BitField*& autoBackground();
    static ::poi::util::BitField*& rotation();
    static ::poi::util::BitField*& showCategoryLabelAsPercentage();
    static ::poi::util::BitField*& showValueAsPercentage();
    static ::poi::util::BitField*& showBubbleSizes();
    static ::poi::util::BitField*& showLabel();
    virtual ::java::lang::Class* getClass0();
};
