// Generated from /POI/java/org/apache/poi/hssf/record/chart/TextRecord.java
#include <org/apache/poi/hssf/record/chart/TextRecord.hpp>

#include <java/lang/NullPointerException.hpp>
#include <java/lang/String.hpp>
#include <java/lang/StringBuffer.hpp>
#include <java/lang/System.hpp>
#include <org/apache/poi/hssf/record/RecordInputStream.hpp>
#include <org/apache/poi/util/BitField.hpp>
#include <org/apache/poi/util/BitFieldFactory.hpp>
#include <org/apache/poi/util/HexDump.hpp>
#include <org/apache/poi/util/LittleEndianOutput.hpp>
#include <Array.hpp>

template<typename T>
static T* npc(T* t)
{
    if(!t) throw new ::java::lang::NullPointerException();
    return t;
}

org::apache::poi::hssf::record::chart::TextRecord::TextRecord(const ::default_init_tag&)
    : super(*static_cast< ::default_init_tag* >(0))
{
    clinit();
}

org::apache::poi::hssf::record::chart::TextRecord::TextRecord() 
    : TextRecord(*static_cast< ::default_init_tag* >(0))
{
    ctor();
}

org::apache::poi::hssf::record::chart::TextRecord::TextRecord(::org::apache::poi::hssf::record::RecordInputStream* in) 
    : TextRecord(*static_cast< ::default_init_tag* >(0))
{
    ctor(in);
}

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::sid;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::dataLabelPlacement()
{
    clinit();
    return dataLabelPlacement_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::dataLabelPlacement_;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::autoColor()
{
    clinit();
    return autoColor_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::autoColor_;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::showKey()
{
    clinit();
    return showKey_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::showKey_;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::showValue()
{
    clinit();
    return showValue_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::showValue_;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::vertical()
{
    clinit();
    return vertical_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::vertical_;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::autoGeneratedText()
{
    clinit();
    return autoGeneratedText_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::autoGeneratedText_;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::generated()
{
    clinit();
    return generated_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::generated_;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::autoLabelDeleted()
{
    clinit();
    return autoLabelDeleted_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::autoLabelDeleted_;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::autoBackground()
{
    clinit();
    return autoBackground_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::autoBackground_;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::rotation()
{
    clinit();
    return rotation_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::rotation_;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::showCategoryLabelAsPercentage()
{
    clinit();
    return showCategoryLabelAsPercentage_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::showCategoryLabelAsPercentage_;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::showValueAsPercentage()
{
    clinit();
    return showValueAsPercentage_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::showValueAsPercentage_;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::showBubbleSizes()
{
    clinit();
    return showBubbleSizes_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::showBubbleSizes_;

org::apache::poi::util::BitField*& org::apache::poi::hssf::record::chart::TextRecord::showLabel()
{
    clinit();
    return showLabel_;
}
org::apache::poi::util::BitField* org::apache::poi::hssf::record::chart::TextRecord::showLabel_;

constexpr int8_t org::apache::poi::hssf::record::chart::TextRecord::HORIZONTAL_ALIGNMENT_LEFT;

constexpr int8_t org::apache::poi::hssf::record::chart::TextRecord::HORIZONTAL_ALIGNMENT_CENTER;

constexpr int8_t org::apache::poi::hssf::record::chart::TextRecord::HORIZONTAL_ALIGNMENT_BOTTOM;

constexpr int8_t org::apache::poi::hssf::record::chart::TextRecord::HORIZONTAL_ALIGNMENT_JUSTIFY;

constexpr int8_t org::apache::poi::hssf::record::chart::TextRecord::VERTICAL_ALIGNMENT_TOP;

constexpr int8_t org::apache::poi::hssf::record::chart::TextRecord::VERTICAL_ALIGNMENT_CENTER;

constexpr int8_t org::apache::poi::hssf::record::chart::TextRecord::VERTICAL_ALIGNMENT_BOTTOM;

constexpr int8_t org::apache::poi::hssf::record::chart::TextRecord::VERTICAL_ALIGNMENT_JUSTIFY;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::DISPLAY_MODE_TRANSPARENT;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::DISPLAY_MODE_OPAQUE;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::ROTATION_NONE;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::ROTATION_TOP_TO_BOTTOM;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::ROTATION_ROTATED_90_DEGREES;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::ROTATION_ROTATED_90_DEGREES_CLOCKWISE;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::DATA_LABEL_PLACEMENT_CHART_DEPENDENT;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::DATA_LABEL_PLACEMENT_OUTSIDE;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::DATA_LABEL_PLACEMENT_INSIDE;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::DATA_LABEL_PLACEMENT_CENTER;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::DATA_LABEL_PLACEMENT_AXIS;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::DATA_LABEL_PLACEMENT_ABOVE;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::DATA_LABEL_PLACEMENT_BELOW;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::DATA_LABEL_PLACEMENT_LEFT;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::DATA_LABEL_PLACEMENT_RIGHT;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::DATA_LABEL_PLACEMENT_AUTO;

constexpr int16_t org::apache::poi::hssf::record::chart::TextRecord::DATA_LABEL_PLACEMENT_USER_MOVED;

void org::apache::poi::hssf::record::chart::TextRecord::ctor()
{
    super::ctor();
}

void org::apache::poi::hssf::record::chart::TextRecord::ctor(::org::apache::poi::hssf::record::RecordInputStream* in)
{
    super::ctor();
    field_1_horizontalAlignment = npc(in)->readByte();
    field_2_verticalAlignment = npc(in)->readByte();
    field_3_displayMode = npc(in)->readShort();
    field_4_rgbColor = npc(in)->readInt();
    field_5_x = npc(in)->readInt();
    field_6_y = npc(in)->readInt();
    field_7_width = npc(in)->readInt();
    field_8_height = npc(in)->readInt();
    field_9_options1 = npc(in)->readShort();
    field_10_indexOfColorValue = npc(in)->readShort();
    field_11_options2 = npc(in)->readShort();
    field_12_textRotation = npc(in)->readShort();
}

java::lang::String* org::apache::poi::hssf::record::chart::TextRecord::toString()
{
    auto buffer = new ::java::lang::StringBuffer();
    npc(buffer)->append(u"[TEXT]\n"_j);
    npc(npc(npc(npc(npc(npc(buffer)->append(u"    .horizontalAlignment  = "_j))->append(u"0x"_j))->append(::org::apache::poi::util::HexDump::toHex(getHorizontalAlignment())))->append(u" ("_j))->append(static_cast< int32_t >(getHorizontalAlignment())))->append(u" )"_j);
    npc(buffer)->append(::java::lang::System::getProperty(u"line.separator"_j));
    npc(npc(npc(npc(npc(npc(buffer)->append(u"    .verticalAlignment    = "_j))->append(u"0x"_j))->append(::org::apache::poi::util::HexDump::toHex(getVerticalAlignment())))->append(u" ("_j))->append(static_cast< int32_t >(getVerticalAlignment())))->append(u" )"_j);
    npc(buffer)->append(::java::lang::System::getProperty(u"line.separator"_j));
    npc(npc(npc(npc(npc(npc(buffer)->append(u"    .displayMode          = "_j))->append(u"0x"_j))->append(::org::apache::poi::util::HexDump::toHex(getDisplayMode())))->append(u" ("_j))->append(static_cast< int32_t >(getDisplayMode())))->append(u" )"_j);
    npc(buffer)->append(::java::lang::System::getProperty(u"line.separator"_j));
    npc(npc(npc(npc(npc(npc(buffer)->append(u"    .rgbColor             = "_j))->append(u"0x"_j))->append(::org::apache::poi::util::HexDump::toHex(getRgbColor())))->append(u" ("_j))->append(getRgbColor()))->append(u" )"_j);
    npc(buffer)->append(::java::lang::System::getProperty(u"line.separator"_j));
    npc(npc(npc(npc(npc(npc(buffer)->append(u"    .x                    = "_j))->append(u"0x"_j))->append(::org::apache::poi::util::HexDump::toHex(getX())))->append(u" ("_j))->append(getX()))->append(u" )"_j);
    npc(buffer)->append(::java::lang::System::getProperty(u"line.separator"_j));
    npc(npc(npc(npc(npc(npc(buffer)->append(u"    .y                    = "_j))->append(u"0x"_j))->append(::org::apache::poi::util::HexDump::toHex(getY())))->append(u" ("_j))->append(getY()))->append(u" )"_j);
    npc(buffer)->append(::java::lang::System::getProperty(u"line.separator"_j));
    npc(npc(npc(npc(npc(npc(buffer)->append(u"    .width                = "_j))->append(u"0x"_j))->append(::org::apache::poi::util::HexDump::toHex(getWidth())))->append(u" ("_j))->append(getWidth()))->append(u" )"_j);
    npc(buffer)->append(::java::lang::System::getProperty(u"line.separator"_j));
    npc(npc(npc(npc(npc(npc(buffer)->append(u"    .height               = "_j))->append(u"0x"_j))->append(::org::apache::poi::util::HexDump::toHex(getHeight())))->append(u" ("_j))->append(getHeight()))->append(u" )"_j);
    npc(buffer)->append(::java::lang::System::getProperty(u"line.separator"_j));
    npc(npc(npc(npc(npc(npc(buffer)->append(u"    .options1             = "_j))->append(u"0x"_j))->append(::org::apache::poi::util::HexDump::toHex(getOptions1())))->append(u" ("_j))->append(static_cast< int32_t >(getOptions1())))->append(u" )"_j);
    npc(buffer)->append(::java::lang::System::getProperty(u"line.separator"_j));
    npc(npc(npc(buffer)->append(u"         .autoColor                = "_j))->append(isAutoColor()))->append(u'\u000a');
    npc(npc(npc(buffer)->append(u"         .showKey                  = "_j))->append(isShowKey()))->append(u'\u000a');
    npc(npc(npc(buffer)->append(u"         .showValue                = "_j))->append(isShowValue()))->append(u'\u000a');
    npc(npc(npc(buffer)->append(u"         .vertical                 = "_j))->append(isVertical()))->append(u'\u000a');
    npc(npc(npc(buffer)->append(u"         .autoGeneratedText        = "_j))->append(isAutoGeneratedText()))->append(u'\u000a');
    npc(npc(npc(buffer)->append(u"         .generated                = "_j))->append(isGenerated()))->append(u'\u000a');
    npc(npc(npc(buffer)->append(u"         .autoLabelDeleted         = "_j))->append(isAutoLabelDeleted()))->append(u'\u000a');
    npc(npc(npc(buffer)->append(u"         .autoBackground           = "_j))->append(isAutoBackground()))->append(u'\u000a');
    npc(npc(npc(buffer)->append(u"         .rotation                 = "_j))->append(static_cast< int32_t >(getRotation())))->append(u'\u000a');
    npc(npc(npc(buffer)->append(u"         .showCategoryLabelAsPercentage     = "_j))->append(isShowCategoryLabelAsPercentage()))->append(u'\u000a');
    npc(npc(npc(buffer)->append(u"         .showValueAsPercentage     = "_j))->append(isShowValueAsPercentage()))->append(u'\u000a');
    npc(npc(npc(buffer)->append(u"         .showBubbleSizes          = "_j))->append(isShowBubbleSizes()))->append(u'\u000a');
    npc(npc(npc(buffer)->append(u"         .showLabel                = "_j))->append(isShowLabel()))->append(u'\u000a');
    npc(npc(npc(npc(npc(npc(buffer)->append(u"    .indexOfColorValue    = "_j))->append(u"0x"_j))->append(::org::apache::poi::util::HexDump::toHex(getIndexOfColorValue())))->append(u" ("_j))->append(static_cast< int32_t >(getIndexOfColorValue())))->append(u" )"_j);
    npc(buffer)->append(::java::lang::System::getProperty(u"line.separator"_j));
    npc(npc(npc(npc(npc(npc(buffer)->append(u"    .options2             = "_j))->append(u"0x"_j))->append(::org::apache::poi::util::HexDump::toHex(getOptions2())))->append(u" ("_j))->append(static_cast< int32_t >(getOptions2())))->append(u" )"_j);
    npc(buffer)->append(::java::lang::System::getProperty(u"line.separator"_j));
    npc(npc(npc(buffer)->append(u"         .dataLabelPlacement       = "_j))->append(static_cast< int32_t >(getDataLabelPlacement())))->append(u'\u000a');
    npc(npc(npc(npc(npc(npc(buffer)->append(u"    .textRotation         = "_j))->append(u"0x"_j))->append(::org::apache::poi::util::HexDump::toHex(getTextRotation())))->append(u" ("_j))->append(static_cast< int32_t >(getTextRotation())))->append(u" )"_j);
    npc(buffer)->append(::java::lang::System::getProperty(u"line.separator"_j));
    npc(buffer)->append(u"[/TEXT]\n"_j);
    return npc(buffer)->toString();
}

void org::apache::poi::hssf::record::chart::TextRecord::serialize(::org::apache::poi::util::LittleEndianOutput* out)
{
    npc(out)->writeByte(field_1_horizontalAlignment);
    npc(out)->writeByte(field_2_verticalAlignment);
    npc(out)->writeShort(field_3_displayMode);
    npc(out)->writeInt(field_4_rgbColor);
    npc(out)->writeInt(field_5_x);
    npc(out)->writeInt(field_6_y);
    npc(out)->writeInt(field_7_width);
    npc(out)->writeInt(field_8_height);
    npc(out)->writeShort(field_9_options1);
    npc(out)->writeShort(field_10_indexOfColorValue);
    npc(out)->writeShort(field_11_options2);
    npc(out)->writeShort(field_12_textRotation);
}

int32_t org::apache::poi::hssf::record::chart::TextRecord::getDataSize()
{
    return int32_t(1) + int32_t(1) + int32_t(2)+ int32_t(4)+ int32_t(4)+ int32_t(4)+ int32_t(4)+ int32_t(4)+ int32_t(2)+ int32_t(2)+ int32_t(2)+ int32_t(2);
}

int16_t org::apache::poi::hssf::record::chart::TextRecord::getSid()
{
    return sid;
}

java::lang::Object* org::apache::poi::hssf::record::chart::TextRecord::clone()
{
    auto rec = new TextRecord();
    npc(rec)->field_1_horizontalAlignment = field_1_horizontalAlignment;
    npc(rec)->field_2_verticalAlignment = field_2_verticalAlignment;
    npc(rec)->field_3_displayMode = field_3_displayMode;
    npc(rec)->field_4_rgbColor = field_4_rgbColor;
    npc(rec)->field_5_x = field_5_x;
    npc(rec)->field_6_y = field_6_y;
    npc(rec)->field_7_width = field_7_width;
    npc(rec)->field_8_height = field_8_height;
    npc(rec)->field_9_options1 = field_9_options1;
    npc(rec)->field_10_indexOfColorValue = field_10_indexOfColorValue;
    npc(rec)->field_11_options2 = field_11_options2;
    npc(rec)->field_12_textRotation = field_12_textRotation;
    return rec;
}

int8_t org::apache::poi::hssf::record::chart::TextRecord::getHorizontalAlignment()
{
    return field_1_horizontalAlignment;
}

void org::apache::poi::hssf::record::chart::TextRecord::setHorizontalAlignment(int8_t field_1_horizontalAlignment)
{
    this->field_1_horizontalAlignment = field_1_horizontalAlignment;
}

int8_t org::apache::poi::hssf::record::chart::TextRecord::getVerticalAlignment()
{
    return field_2_verticalAlignment;
}

void org::apache::poi::hssf::record::chart::TextRecord::setVerticalAlignment(int8_t field_2_verticalAlignment)
{
    this->field_2_verticalAlignment = field_2_verticalAlignment;
}

int16_t org::apache::poi::hssf::record::chart::TextRecord::getDisplayMode()
{
    return field_3_displayMode;
}

void org::apache::poi::hssf::record::chart::TextRecord::setDisplayMode(int16_t field_3_displayMode)
{
    this->field_3_displayMode = field_3_displayMode;
}

int32_t org::apache::poi::hssf::record::chart::TextRecord::getRgbColor()
{
    return field_4_rgbColor;
}

void org::apache::poi::hssf::record::chart::TextRecord::setRgbColor(int32_t field_4_rgbColor)
{
    this->field_4_rgbColor = field_4_rgbColor;
}

int32_t org::apache::poi::hssf::record::chart::TextRecord::getX()
{
    return field_5_x;
}

void org::apache::poi::hssf::record::chart::TextRecord::setX(int32_t field_5_x)
{
    this->field_5_x = field_5_x;
}

int32_t org::apache::poi::hssf::record::chart::TextRecord::getY()
{
    return field_6_y;
}

void org::apache::poi::hssf::record::chart::TextRecord::setY(int32_t field_6_y)
{
    this->field_6_y = field_6_y;
}

int32_t org::apache::poi::hssf::record::chart::TextRecord::getWidth()
{
    return field_7_width;
}

void org::apache::poi::hssf::record::chart::TextRecord::setWidth(int32_t field_7_width)
{
    this->field_7_width = field_7_width;
}

int32_t org::apache::poi::hssf::record::chart::TextRecord::getHeight()
{
    return field_8_height;
}

void org::apache::poi::hssf::record::chart::TextRecord::setHeight(int32_t field_8_height)
{
    this->field_8_height = field_8_height;
}

int16_t org::apache::poi::hssf::record::chart::TextRecord::getOptions1()
{
    return field_9_options1;
}

void org::apache::poi::hssf::record::chart::TextRecord::setOptions1(int16_t field_9_options1)
{
    this->field_9_options1 = field_9_options1;
}

int16_t org::apache::poi::hssf::record::chart::TextRecord::getIndexOfColorValue()
{
    return field_10_indexOfColorValue;
}

void org::apache::poi::hssf::record::chart::TextRecord::setIndexOfColorValue(int16_t field_10_indexOfColorValue)
{
    this->field_10_indexOfColorValue = field_10_indexOfColorValue;
}

int16_t org::apache::poi::hssf::record::chart::TextRecord::getOptions2()
{
    return field_11_options2;
}

void org::apache::poi::hssf::record::chart::TextRecord::setOptions2(int16_t field_11_options2)
{
    this->field_11_options2 = field_11_options2;
}

int16_t org::apache::poi::hssf::record::chart::TextRecord::getTextRotation()
{
    return field_12_textRotation;
}

void org::apache::poi::hssf::record::chart::TextRecord::setTextRotation(int16_t field_12_textRotation)
{
    this->field_12_textRotation = field_12_textRotation;
}

void org::apache::poi::hssf::record::chart::TextRecord::setAutoColor(bool value)
{
    field_9_options1 = npc(autoColor_)->setShortBoolean(field_9_options1, value);
}

bool org::apache::poi::hssf::record::chart::TextRecord::isAutoColor()
{
    return npc(autoColor_)->isSet(field_9_options1);
}

void org::apache::poi::hssf::record::chart::TextRecord::setShowKey(bool value)
{
    field_9_options1 = npc(showKey_)->setShortBoolean(field_9_options1, value);
}

bool org::apache::poi::hssf::record::chart::TextRecord::isShowKey()
{
    return npc(showKey_)->isSet(field_9_options1);
}

void org::apache::poi::hssf::record::chart::TextRecord::setShowValue(bool value)
{
    field_9_options1 = npc(showValue_)->setShortBoolean(field_9_options1, value);
}

bool org::apache::poi::hssf::record::chart::TextRecord::isShowValue()
{
    return npc(showValue_)->isSet(field_9_options1);
}

void org::apache::poi::hssf::record::chart::TextRecord::setVertical(bool value)
{
    field_9_options1 = npc(vertical_)->setShortBoolean(field_9_options1, value);
}

bool org::apache::poi::hssf::record::chart::TextRecord::isVertical()
{
    return npc(vertical_)->isSet(field_9_options1);
}

void org::apache::poi::hssf::record::chart::TextRecord::setAutoGeneratedText(bool value)
{
    field_9_options1 = npc(autoGeneratedText_)->setShortBoolean(field_9_options1, value);
}

bool org::apache::poi::hssf::record::chart::TextRecord::isAutoGeneratedText()
{
    return npc(autoGeneratedText_)->isSet(field_9_options1);
}

void org::apache::poi::hssf::record::chart::TextRecord::setGenerated(bool value)
{
    field_9_options1 = npc(generated_)->setShortBoolean(field_9_options1, value);
}

bool org::apache::poi::hssf::record::chart::TextRecord::isGenerated()
{
    return npc(generated_)->isSet(field_9_options1);
}

void org::apache::poi::hssf::record::chart::TextRecord::setAutoLabelDeleted(bool value)
{
    field_9_options1 = npc(autoLabelDeleted_)->setShortBoolean(field_9_options1, value);
}

bool org::apache::poi::hssf::record::chart::TextRecord::isAutoLabelDeleted()
{
    return npc(autoLabelDeleted_)->isSet(field_9_options1);
}

void org::apache::poi::hssf::record::chart::TextRecord::setAutoBackground(bool value)
{
    field_9_options1 = npc(autoBackground_)->setShortBoolean(field_9_options1, value);
}

bool org::apache::poi::hssf::record::chart::TextRecord::isAutoBackground()
{
    return npc(autoBackground_)->isSet(field_9_options1);
}

void org::apache::poi::hssf::record::chart::TextRecord::setRotation(int16_t value)
{
    field_9_options1 = npc(rotation_)->setShortValue(field_9_options1, value);
}

int16_t org::apache::poi::hssf::record::chart::TextRecord::getRotation()
{
    return npc(rotation_)->getShortValue(field_9_options1);
}

void org::apache::poi::hssf::record::chart::TextRecord::setShowCategoryLabelAsPercentage(bool value)
{
    field_9_options1 = npc(showCategoryLabelAsPercentage_)->setShortBoolean(field_9_options1, value);
}

bool org::apache::poi::hssf::record::chart::TextRecord::isShowCategoryLabelAsPercentage()
{
    return npc(showCategoryLabelAsPercentage_)->isSet(field_9_options1);
}

void org::apache::poi::hssf::record::chart::TextRecord::setShowValueAsPercentage(bool value)
{
    field_9_options1 = npc(showValueAsPercentage_)->setShortBoolean(field_9_options1, value);
}

bool org::apache::poi::hssf::record::chart::TextRecord::isShowValueAsPercentage()
{
    return npc(showValueAsPercentage_)->isSet(field_9_options1);
}

void org::apache::poi::hssf::record::chart::TextRecord::setShowBubbleSizes(bool value)
{
    field_9_options1 = npc(showBubbleSizes_)->setShortBoolean(field_9_options1, value);
}

bool org::apache::poi::hssf::record::chart::TextRecord::isShowBubbleSizes()
{
    return npc(showBubbleSizes_)->isSet(field_9_options1);
}

void org::apache::poi::hssf::record::chart::TextRecord::setShowLabel(bool value)
{
    field_9_options1 = npc(showLabel_)->setShortBoolean(field_9_options1, value);
}

bool org::apache::poi::hssf::record::chart::TextRecord::isShowLabel()
{
    return npc(showLabel_)->isSet(field_9_options1);
}

void org::apache::poi::hssf::record::chart::TextRecord::setDataLabelPlacement(int16_t value)
{
    field_11_options2 = npc(dataLabelPlacement_)->setShortValue(field_11_options2, value);
}

int16_t org::apache::poi::hssf::record::chart::TextRecord::getDataLabelPlacement()
{
    return npc(dataLabelPlacement_)->getShortValue(field_11_options2);
}

extern java::lang::Class *class_(const char16_t *c, int n);

java::lang::Class* org::apache::poi::hssf::record::chart::TextRecord::class_()
{
    static ::java::lang::Class* c = ::class_(u"org.apache.poi.hssf.record.chart.TextRecord", 43);
    return c;
}

void org::apache::poi::hssf::record::chart::TextRecord::clinit()
{
    super::clinit();
    static bool in_cl_init = false;
struct clinit_ {
    clinit_() {
        in_cl_init = true;
        dataLabelPlacement_ = ::org::apache::poi::util::BitFieldFactory::getInstance(15);
        autoColor_ = ::org::apache::poi::util::BitFieldFactory::getInstance(1);
        showKey_ = ::org::apache::poi::util::BitFieldFactory::getInstance(2);
        showValue_ = ::org::apache::poi::util::BitFieldFactory::getInstance(4);
        vertical_ = ::org::apache::poi::util::BitFieldFactory::getInstance(8);
        autoGeneratedText_ = ::org::apache::poi::util::BitFieldFactory::getInstance(16);
        generated_ = ::org::apache::poi::util::BitFieldFactory::getInstance(32);
        autoLabelDeleted_ = ::org::apache::poi::util::BitFieldFactory::getInstance(64);
        autoBackground_ = ::org::apache::poi::util::BitFieldFactory::getInstance(128);
        rotation_ = ::org::apache::poi::util::BitFieldFactory::getInstance(1792);
        showCategoryLabelAsPercentage_ = ::org::apache::poi::util::BitFieldFactory::getInstance(2048);
        showValueAsPercentage_ = ::org::apache::poi::util::BitFieldFactory::getInstance(4096);
        showBubbleSizes_ = ::org::apache::poi::util::BitFieldFactory::getInstance(8192);
        showLabel_ = ::org::apache::poi::util::BitFieldFactory::getInstance(16384);
    }
};

    if(!in_cl_init) {
        static clinit_ clinit_instance;
    }
}

int32_t org::apache::poi::hssf::record::chart::TextRecord::serialize(int32_t offset, ::int8_tArray* data)
{
    return super::serialize(offset, data);
}

int8_tArray* org::apache::poi::hssf::record::chart::TextRecord::serialize()
{
    return super::serialize();
}

java::lang::Class* org::apache::poi::hssf::record::chart::TextRecord::getClass0()
{
    return class_();
}

